import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Realtime - collaborative editing for Obsidian.
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
});

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  const wasmSrc = "node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.wasm";
  if (!existsSync(wasmSrc)) {
    throw new Error(`Missing cr-sqlite WASM asset: ${wasmSrc}`);
  }
  copyFileSync(wasmSrc, "crsqlite.wasm");
  process.exit(0);
}
