import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";

/**
 * Ship the cr-sqlite WASM alongside main.js so the synced-SQLite plugin API can
 * load it from the plugin directory (and so `release.mjs` can upload it as a
 * release asset). The runtime resolves it from `${manifest.dir}/crsqlite.wasm`.
 *
 * VERSION PIN: the WASM comes from `@vlcn.io/crsqlite-wasm` in package.json and
 * must stay on the same cr-sqlite minor line as the server's loadable extension
 * (`CRSQLITE_VERSION` in server/Dockerfile, currently 0.16.x) — they share the
 * `crsqlite-1` sync format (src/pluginDb/types.ts SYNC_FORMAT). Bump all
 * together: package.json dep, server/Dockerfile ARG + checksums, SYNC_FORMAT if
 * the wire format changes.
 */
function copyCrsqliteWasm() {
  const src = "node_modules/@vlcn.io/crsqlite-wasm/dist/crsqlite.wasm";
  const dest = "crsqlite.wasm";
  if (existsSync(src)) {
    copyFileSync(src, dest);
    console.log("Copied crsqlite.wasm");
  } else {
    console.warn("crsqlite.wasm not found at", src, "- plugin SQL API will download it at runtime");
  }
}



const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Realtime - collaborative editing for Obsidian.
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  // Inline the cr-sqlite WASM as a data URL so the synced-SQLite API works without
  // a separate asset (BRAT/manual installs only ship main.js; mobile has no fs).
  // The cr-sqlite package loads it via `new URL("crsqlite.wasm", import.meta.url)`,
  // which esbuild rewrites to this inlined data URL — a single embedded copy.
  loader: { ".wasm": "dataurl" },
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  minify: prod,
  outfile: "main.js",
});

copyCrsqliteWasm();

if (watch) {
  await context.watch();
} else {
  await context.rebuild();
  process.exit(0);
}
