[package]
name = "realtime-server-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
realtime-server = { path = "..", features = ["fuzzing"] }

[[bin]]
name = "protocol"
path = "fuzz_targets/protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "storage"
path = "fuzz_targets/storage.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
